---
title: "Cyclistic"
subtitle: "Analysis of difference in ridership patterns between casual and member customers"
author: "Bryan Johns"
date: "`r format(Sys.Date(), '%Y-%m')`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    css: ./resources/css/styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Google Data Analytics Capstone

A hypothetical data analysis project, answering a business question for a fictional bikeshare company, analyzing customer behavior and concluding with recommendations to assist in converting casual customers into annual members.

Google's [Data Analytics certificate](https://www.coursera.org/professional-certificates/google-data-analytics) provides an introductory training, covering spreadsheets, SQL, Tableau, and R. The capstone is optional. I used R for my analysis, to further practice that programming language, supplementing my background primarily in Python.

This report follows the certificate's framework for data analysis: Ask, Prepare, Process, Analyze, Share, Act. It corresponds to the following deliverables:

1. A clear statement of the business task (Ask)
2. A description of all data sources used (Prepare)
3. Documentation of any cleaning or manipulation of data (Process)
4. A summary of the data analysis (Analyze)
5. Supporting visualizations and key findings (Share)
6. Top three recommendations based on analysis (Act)

## Scenario

See `./resources/Case Study 1_How does a bike-share navigate speedy success.pdf`. Quoted from the Google Data Analytics Capstone:

<blockquote>You are a junior data analyst working on the marketing analyst team at Cyclistic, a bike-share
company in Chicago. The director of marketing believes the company’s future success
depends on maximizing the number of annual memberships. Therefore, your team wants to
understand how casual riders and annual members use Cyclistic bikes dierently. From these
insights, your team will design a new marketing strategy to convert casual riders into annual
members. But first, Cyclistic executives must approve your recommendations, so they must be
backed up with compelling data insights and professional data visualizations.

Characters and teams

● Cyclistic: A bike-share program that features more than 5,800 bicycles and 600
docking stations. Cyclistic sets itself apart by also offering reclining bikes, hand
tricycles, and cargo bikes, making bike-share more inclusive to people with disabilities
and riders who can’t use a standard two-wheeled bike. The majority of riders opt for
traditional bikes; about 8% of riders use the assistive options. Cyclistic users are more
likely to ride for leisure, but about 30% use the bikes to commute to work each day.

● Lily Moreno: The director of marketing and your manager. Moreno is responsible for
the development of campaigns and initiatives to promote the bike-share program.
These may include email, social media, and other channels.

● Cyclistic marketing analytics team: A team of data analysts who are responsible for
collecting, analyzing, and reporting data that helps guide Cyclistic marketing strategy.
You joined this team six months ago and have been busy learning about Cyclistic’s
mission and business goals—as well as how you, as a junior data analyst, can help
Cyclistic achieve them.

● Cyclistic executive team: The notoriously detail-oriented executive team will decide
whether to approve the recommended marketing program.

About the company

In 2016, Cyclistic launched a successful bike-share offering. Since then, the program has grown
to a fleet of 5,824 bicycles that are geotracked and locked into a network of 692 stations across
Chicago. The bikes can be unlocked from one station and returned to any other station in the
system anytime.

Until now, Cyclistic’s marketing strategy relied on building general awareness and appealing to
broad consumer segments. One approach that helped make these things possible was the
flexibility of its pricing plans: single-ride passes, full-day passes, and annual memberships.
Customers who purchase single-ride or full-day passes are referred to as casual riders.
Customers who purchase annual memberships are Cyclistic members.

Cyclistic’s finance analysts have concluded that annual members are much more profitable
than casual riders. Although the pricing flexibility helps Cyclistic attract more customers,
Moreno believes that maximizing the number of annual members will be key to future growth.
Rather than creating a marketing campaign that targets all-new customers, Moreno believes
there is a solid opportunity to convert casual riders into members. She notes that casual riders
are already aware of the Cyclistic program and have chosen Cyclistic for their mobility needs.

Moreno has set a clear goal: Design marketing strategies aimed at converting casual riders into
annual members. In order to do that, however, the team needs to better understand how
annual members and casual riders differ, why casual riders would buy a membership, and how
digital media could affect their marketing tactics. Moreno and her team are interested in
analyzing the Cyclistic historical bike trip data to identify trends.

Note that data-privacy issues prohibit you from using riders’ personally identifiable information.
This means that you won’t be able to connect pass purchases to credit card numbers to
determine if casual riders live in the Cyclistic service area or if they have purchased multiple
single passes.

Three questions will guide the future marketing program:

1. How do annual members and casual riders use Cyclistic bikes differently?
2. Why would casual riders buy Cyclistic annual memberships?
3. How can Cyclistic use digital media to influence casual riders to become members?
<br><br>

Moreno has assigned you the first question to answer: How do annual members and casual
riders use Cyclistic bikes differently?
</blockquote>

## Ask

Deliverable: A clear statement of the business task

How do annual members and casual riders use Cyclistic bikes differently? 

Base the analysis on Cyclistic historical bike trip data.

## Prepare

Deliverable: A description of all data sources used

Google provided the [data](https://divvy-tripdata.s3.amazonaws.com/index.html), meaning Lyft and Divvy provided them with data from Chicago.

> The [data](https://divvy-tripdata.s3.amazonaws.com/index.html) has been made available by Motivate International Inc. under this [license](https://divvybikes.com/data-license-agreement).

I used data for 2019, because it has info on gender and birthyear. Pretend that was last year and the data is current and useful.

## Process

Deliverable: Documentation of any cleaning or manipulation of data

Google provided a starter template to clean the data. See `data_cleaning_v1.R`.

Google's template covered only Q1 2019 and Q1 2020. I wanted to have all of 2019 available, so I modified the script to clean individual quarters of Cyclistic data. To join Q1 2019 and Q1 2020, Google's template removed trip duration, gender, and birth year from 2019, station latitude and longitude from 2020. I wanted to keep that info, so I dropped 2020 (lacking gender and birthyear), and added 2020's lat/lng to 2019.

Data cleaning consisted of:

● Extracting station latitude and longitude from 2020 and adding it to start and end stations in 2019 (labeling all but 366 of almost 4 million rows).

● Removing "tripduration" from 2019.

● Consolidating the "member_casual" column from four labels to two ("member" and "casual"), instead of the original two names for members ("member" and "Subscriber") and two names for casual riders ("Customer" and "casual").

● Extracting day, month, year, season, and day of the week from the start date and creating columns for each, to provide additional opportunities to aggregate the data.

● Adding a calculated field ("ride_length") for length of ride since the 2020Q1 data did not have
the "tripduration" column. This briefly catastrophically halted data analysis, as ride length was calculated in minutes for 2019, and seconds in 2020.

● Remvoing rides where ride_length shows up as negative, including several hundred rides where the company took bikes out of circulation for Quality Control reasons.

## Analyze

Deliverable: A summary of the data analysis

See `./resources/scratch_pad.Rmd`. Appropriately named, the Scratch Pad is where I played with the data.

Casual riders go longer than members (one hour vs 15 mins).

More member rides than casual rides (3 million vs 1 million).

Ridership peaks in August and nadirs in February, porportionally for both groups. Winter is dead. Crickets for activity.

Casual riders ride late morning, peaking late afternoon, especially Saturday, quite a bit Sunday. Weekend Warriors. Members have two peaks - weekdays at 8am and 5pm. Commuters. They also ride roughly the same on weekends, a gentle curve from late morning to late afternoon.

Top 10 stations! Members riders go to the "Loop". Casual riders seem to hit tourist / leisure destinations (I assume? Must research Chicago landmarks. "Milleniumn Park", "Shedd Aquarium", "Theater on the Lake", "Dusable Harbor", and "Adler Planetarium" sound like destinations for the occasional bike rider).

Members are slightly older, peaking in 30-35. Casual in 25-30.

More men ride than women. Maybe an opportunity there.


## Share

Deliverable: Supporting visualizations and key findings

## Act

Deliverable: Top three recommendations based on analysis
